add slug to movie entity
Mysteradev/celestaria-backend pull request #8
Opened 2020-10-10 18:46 UTC by mathias73

close #7

2020-10-10 20:26 UTC, Kayoshi-dev requested changes
Petites erreurs dans l'ajout de la propriété $movieSlug et de son getter et setter. 

Aussi, la génération du slug va se faire côté Backend, il faudrait regarder comment faire ça, je te mets le lien d'une lib qui pourrait aider à la génération de ce slug : 

Lib pour la génération de slug, prenant en compte divers langages (Arabe, Chinois etc) : https://github.com/cocur/slugify

2020-10-10 20:26 UTC, Kayoshi-dev commented on src/Entity/Movie.php
> +        $this->videoUrl = $videoUrl;
* Mauvais nom de méthode
* Mauvais nom de paramètre

et ligne 93 devrait être : $this->movieSlug = $movieSlug

2020-10-10 20:26 UTC, Kayoshi-dev commented on src/Entity/Movie.php
> +    public function getVideoSlug(): ?string
ça devrait être getMovieSlug

2020-10-10 20:26 UTC, Kayoshi-dev commented on src/Entity/Movie.php
> +        return $this->videoUrl;
devrait retourner $this->movieSlug

2020-10-10 20:32 UTC, Kayoshi-dev commented
Il est aussi nécessaire de pouvoir chercher un film par son slug, je te laisse check côté documentation ApiPlatform pour savoir comment faire ça : https://api-platform.com/docs/core/filters/

2020-10-10 22:45 UTC, Kayoshi-dev reviewed
Méthods good pour le moment, il faut ajouter un Filtre pour chercher par titre de films stp. (Pour toi stp)
On a également une erreur lorsque l'on veut ajouter un nouveau film en méthode POST, étant donné qu'on ne renseigne pas de slug dans l'envoie de la requête. (Je m'occupe de cette partie)

2020-10-11 17:16 UTC, Kayoshi-dev requested changes
Je t'ai mis quelques petites modifs à faire, étant donné qu'on utilise Doctrine y'a pas besoin de s'embêter autant.

Globalement tu trouveras tout ce dont tu as besoin ici : https://api-platform.com/docs/core/filters/#search-filter

2020-10-11 17:16 UTC, Kayoshi-dev commented on config/services.yaml
> +    tags: [ 'api_platform.filter' ]
Je pense que y'a pas besoin de faire aussi compliqué, vu qu'on utilise Doctrine tu peux te passer de cette partie.

Tu peux directement aller chercher ici : https://api-platform.com/docs/core/filters/#search-filter

2020-10-11 17:16 UTC, Kayoshi-dev commented on src/Entity/Movie.php
> + *     attributes={"filters"="movie.title_filter"}
Pareil que le commentaire du dessus, non nécessaire si l'on utilise Doctrine !

2020-10-11 17:16 UTC, Kayoshi-dev commented on src/Entity/Movie.php
> + * @ApiFilter(Movie::class, properties={"title" = "start"})
On aura besoin d'un @ApiFilter mais avec un filtre différent, comme au dessus tu peux check ici : h
ttps://api-platform.com/docs/core/filters/#search-filter

Aussi je pense qu'on filtrera les titres avec quelques choses du genre LIKE %recherche%, cherche dans les matching strategies dans la doc

2020-10-12 18:09 UTC, mathias73 commented on src/Entity/Movie.php
> + * @ApiFilter(Movie::class, properties={"title" = "start"})
J'ai fais des modifs, je te laisse check si ça va

2020-10-14 19:14 UTC, Kayoshi-dev approved these changes
Good pour moi, j'ai testé sur mon env et j'ai bien les données qu'il me faut. Je merge

2020-10-14 20:31 UTC, merged